#!/bin/sh

# This is a wrapper script for lf that allows it to create image previews with
# ueberzug. This works in concert with the lf configuration file and the
# lf-cleaner script.

set -e

UEBERZUGPP_PID=0
UEBERZUGPP_SOCKET=""

cleanup() {
    exec 3>&-
    kill -TERM $UEBERZUG_PID
}

if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
	lf "$@"
else
    [ ! -d "$HOME/.cache/lf" ] && mkdir --parents "$HOME/.cache/lf"
    ueberzugpp layer --silent --no-stdin --use-escape-codes &
    UEBERZUGPP_PID=$!
    UEBERZUGPP_SOCKET="/tmp/ueberzugpp-${UEBERZUG_PID}.socket"
    export UEBERZUGPP_PID UEBERZUGPP_SOCKET
    sleep 0.2
    trap cleanup HUP INT QUIT TERM PWR EXIT
    lf "$@" 3>&-
fi
