#!/bin/bash

ueberzugpp layer --no-stdin --silent --use-escape-codes &
UB_PID=$!

# sleep some time for U++ startup
sleep 0.2

export SOCKET=/tmp/ueberzugpp-$UB_PID.socket
export X=$(($(tput cols) / 2 + 1))

# run fzf with preview
fzf --preview='ueberzugpp cmd -s $SOCKET -i fzfpreview -a add -x $X -y 1 --max-height $FZF_PREVIEW_COLUMNS --max-height $FZF_PREVIEW_LINES -f {}' --reverse "$@"

kill -TERM $UB_PID
